
server:
  port: 8081

# custom property
# security.signing-key=123

security:
  oauth2:
    resource:
      jwt:
       key-value: KdklKDMfkLKfjeilakdxLKSDJfielKDJfyi
    

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka/