

server:
  port: 8083


spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      jwt:
        key-value: KdklKDMfkLKfjeilakdxLKSDJfielKDJfyi
    client:
     client-id: oauthclient
     client-secret: secret
     access-token-uri: http://localhost:8080/uaa/oauth/token 
     grant-type: client_credentials
     scope: server
